"""Product persona registry — defines what each vendor stack looks like.

A persona drives:
  - which log schema generators are selected
  - which vendor API emulation router handles inbound SOAR calls
  - the exact field names and event formats in generated logs
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class PersonaDefinition:
    key: str                        # machine key, e.g. "crowdstrike_falcon"
    vendor: str                     # display vendor name
    product: str                    # display product name
    category: str                   # edr | siem | idp | firewall | network
    api_prefix: str                 # route prefix, e.g. "/api/vendor/crowdstrike"
    log_source_types: list[str]     # source_type values generated by this persona
    alert_format: str               # "crowdstrike" | "splunk" | "defender" etc.
    auth_scheme: str                # "oauth2" | "basic" | "api_key" | "bearer"
    capabilities: list[str]         # response actions this persona supports
    field_aliases: dict[str, str]   # canonical_field → vendor_field translation
    metadata: dict[str, Any] = field(default_factory=dict)


# ── EDR Personas ──────────────────────────────────────────────────────────────

CROWDSTRIKE_FALCON = PersonaDefinition(
    key="crowdstrike_falcon",
    vendor="CrowdStrike",
    product="Falcon EDR",
    category="edr",
    api_prefix="/api/vendor/crowdstrike",
    log_source_types=["edr", "crowdstrike_edr", "crowdstrike"],
    alert_format="crowdstrike",
    auth_scheme="oauth2",
    capabilities=[
        "isolate_host", "release_host", "block_hash", "unblock_hash",
        "kill_process", "get_detections", "list_endpoints", "run_script",
        "get_process_tree", "collect_file",
    ],
    field_aliases={
        "hostname": "ComputerName",
        "process_name": "FileName",
        "command_line": "CommandLine",
        "process_id": "ProcessId",
        "parent_process": "ParentImageFileName",
        "user": "UserName",
        "sha256": "SHA256HashData",
        "alert_id": "DetectionId",
        "severity": "SeverityName",
    },
    metadata={
        "oauth2_token_url": "/oauth2/token",
        "base_path": "/api/vendor/crowdstrike",
        "docs": "https://falcon.crowdstrike.com/documentation/46/crowdstrike-oauth2-based-apis",
    },
)

CARBON_BLACK = PersonaDefinition(
    key="carbon_black",
    vendor="VMware Carbon Black",
    product="Carbon Black EDR",
    category="edr",
    api_prefix="/api/vendor/carbonblack",
    log_source_types=["edr", "carbonblack"],
    alert_format="carbonblack",
    auth_scheme="api_key",
    capabilities=[
        "isolate_host", "release_host", "ban_hash", "kill_process",
        "get_processes", "list_sensors", "execute_command",
    ],
    field_aliases={
        "hostname": "hostname",
        "process_name": "process_name",
        "command_line": "cmdline",
        "process_id": "pid",
        "user": "username",
        "sha256": "md5",  # CB uses md5 primarily
        "alert_id": "id",
    },
    metadata={"base_path": "/api/vendor/carbonblack"},
)

MICROSOFT_DEFENDER = PersonaDefinition(
    key="microsoft_defender",
    vendor="Microsoft",
    product="Defender for Endpoint",
    category="edr",
    api_prefix="/api/vendor/defender",
    log_source_types=["edr", "defender", "windows_eventlog", "sysmon"],
    alert_format="defender",
    auth_scheme="bearer",
    capabilities=[
        "isolate_host", "release_host", "block_hash", "unblock_hash",
        "restrict_app_execution", "run_antivirus_scan", "get_alerts",
        "list_machines", "stop_and_quarantine_file",
    ],
    field_aliases={
        "hostname": "computerDnsName",
        "process_name": "processCommandLine",
        "user": "loggedOnUsers",
        "sha256": "sha256",
        "alert_id": "id",
        "severity": "severity",
    },
    metadata={
        "base_path": "/api/vendor/defender",
        "graph_api": "https://api.securitycenter.microsoft.com",
    },
)

SENTINELONE = PersonaDefinition(
    key="sentinelone",
    vendor="SentinelOne",
    product="Singularity EDR",
    category="edr",
    api_prefix="/api/vendor/sentinelone",
    log_source_types=["edr", "sentinelone"],
    alert_format="sentinelone",
    auth_scheme="api_key",
    capabilities=[
        "isolate_host", "release_host", "block_hash", "kill_process",
        "quarantine_file", "get_threats", "list_agents",
    ],
    field_aliases={
        "hostname": "computerName",
        "process_name": "processName",
        "sha256": "sha256",
        "alert_id": "id",
    },
    metadata={"base_path": "/api/vendor/sentinelone"},
)

ELASTIC_EDR = PersonaDefinition(
    key="elastic_edr",
    vendor="Elastic",
    product="Elastic Defend (EDR)",
    category="edr",
    api_prefix="/api/vendor/elastic",
    log_source_types=["edr", "elastic"],
    alert_format="elastic_edr",
    auth_scheme="api_key",
    capabilities=["isolate_host", "kill_process", "get_alerts"],
    field_aliases={
        "hostname": "host.hostname",
        "process_name": "process.name",
        "command_line": "process.command_line",
        "user": "user.name",
        "sha256": "process.hash.sha256",
    },
    metadata={"base_path": "/api/vendor/elastic"},
)


# ── SIEM Personas ─────────────────────────────────────────────────────────────

SPLUNK_ES = PersonaDefinition(
    key="splunk_es",
    vendor="Splunk",
    product="Splunk Enterprise Security",
    category="siem",
    api_prefix="/api/vendor/splunk",
    log_source_types=["siem", "splunk"],
    alert_format="splunk",
    auth_scheme="basic",
    capabilities=[
        "search_spl", "deploy_saved_search", "create_notable", "suppress_event",
        "get_notable_events", "list_saved_searches", "run_adaptive_response",
    ],
    field_aliases={
        "timestamp": "_time",
        "hostname": "host",
        "source_type": "sourcetype",
        "index": "index",
        "message": "_raw",
    },
    metadata={
        "base_path": "/api/vendor/splunk",
        "query_language": "spl",
        "search_api": "/services/search/jobs",
    },
)

QRADAR = PersonaDefinition(
    key="qradar",
    vendor="IBM",
    product="QRadar SIEM",
    category="siem",
    api_prefix="/api/vendor/qradar",
    log_source_types=["siem", "qradar"],
    alert_format="qradar",
    auth_scheme="api_key",
    capabilities=[
        "search_aql", "list_offenses", "close_offense", "create_reference_set",
        "add_to_reference_set", "deploy_custom_rule", "get_log_sources",
    ],
    field_aliases={
        "timestamp": "startTime",
        "hostname": "sourceIP",
        "severity": "severity",
        "event_id": "eventId",
    },
    metadata={
        "base_path": "/api/vendor/qradar",
        "query_language": "aql",
        "search_api": "/api/ariel/searches",
    },
)

PALO_ALTO_XSIAM = PersonaDefinition(
    key="palo_alto_xsiam",
    vendor="Palo Alto Networks",
    product="XSIAM",
    category="siem",
    api_prefix="/api/vendor/xsiam",
    log_source_types=["siem", "xsiam", "xdr"],
    alert_format="xsiam",
    auth_scheme="api_key",
    capabilities=[
        "search_xql", "list_incidents", "get_alerts", "isolate_endpoint",
        "block_indicators", "run_script", "quarantine_file",
    ],
    field_aliases={
        "hostname": "agent_hostname",
        "alert_id": "alert_id",
        "severity": "severity",
    },
    metadata={
        "base_path": "/api/vendor/xsiam",
        "query_language": "xql",
        "search_api": "/public_api/v1/xql/start_xql_query",
    },
)

MICROSOFT_SENTINEL = PersonaDefinition(
    key="microsoft_sentinel",
    vendor="Microsoft",
    product="Microsoft Sentinel",
    category="siem",
    api_prefix="/api/vendor/sentinel",
    log_source_types=["siem", "sentinel"],
    alert_format="sentinel",
    auth_scheme="bearer",
    capabilities=[
        "search_kql", "list_incidents", "create_incident", "close_incident",
        "create_watchlist", "deploy_analytics_rule", "run_playbook",
    ],
    field_aliases={
        "timestamp": "TimeGenerated",
        "hostname": "Computer",
        "severity": "AlertSeverity",
    },
    metadata={
        "base_path": "/api/vendor/sentinel",
        "query_language": "kql",
    },
)

ELASTIC_SIEM = PersonaDefinition(
    key="elastic_siem",
    vendor="Elastic",
    product="Elastic SIEM (Security)",
    category="siem",
    api_prefix="/api/vendor/elastic_siem",
    log_source_types=["siem", "elastic_siem"],
    alert_format="elastic",
    auth_scheme="api_key",
    capabilities=["search_eql", "list_alerts", "create_detection_rule"],
    field_aliases={
        "hostname": "host.hostname",
        "user": "user.name",
        "timestamp": "@timestamp",
    },
    metadata={"base_path": "/api/vendor/elastic_siem", "query_language": "eql"},
)


# ── IdP Personas ──────────────────────────────────────────────────────────────

OKTA = PersonaDefinition(
    key="okta",
    vendor="Okta",
    product="Okta Identity Cloud",
    category="idp",
    api_prefix="/api/vendor/okta",
    log_source_types=["auth", "okta", "okta_identity"],
    alert_format="okta",
    auth_scheme="api_key",
    capabilities=[
        "disable_user", "enable_user", "reset_password", "expire_sessions",
        "revoke_tokens", "list_users", "get_user_sessions", "lock_user",
    ],
    field_aliases={
        "user": "actor.alternateId",
        "event_type": "eventType",
        "result": "outcome.result",
        "ip": "securityContext.ipAddress",
    },
    metadata={"base_path": "/api/vendor/okta"},
)

MICROSOFT_ENTRA = PersonaDefinition(
    key="microsoft_entra",
    vendor="Microsoft",
    product="Entra ID (Azure AD)",
    category="idp",
    api_prefix="/api/vendor/entra",
    log_source_types=["auth", "entra_id", "azure_ad"],
    alert_format="entra",
    auth_scheme="bearer",
    capabilities=[
        "disable_user", "enable_user", "reset_password", "revoke_sessions",
        "list_users", "get_signin_logs", "conditional_access",
    ],
    field_aliases={
        "user": "userPrincipalName",
        "ip": "ipAddress",
        "result": "status.errorCode",
    },
    metadata={"base_path": "/api/vendor/entra"},
)


# ── Firewall Personas ─────────────────────────────────────────────────────────

PALO_ALTO_NGFW = PersonaDefinition(
    key="palo_alto_ngfw",
    vendor="Palo Alto Networks",
    product="NGFW",
    category="firewall",
    api_prefix="/api/vendor/palo_alto",
    log_source_types=["firewall", "palo_alto"],
    alert_format="palo_alto",
    auth_scheme="api_key",
    capabilities=[
        "block_ip", "unblock_ip", "block_url", "add_to_blocklist",
        "get_traffic_logs", "create_security_policy",
    ],
    field_aliases={
        "src_ip": "src",
        "dst_ip": "dst",
        "action": "action",
        "rule": "rule",
    },
    metadata={"base_path": "/api/vendor/palo_alto"},
)

FORTINET = PersonaDefinition(
    key="fortinet",
    vendor="Fortinet",
    product="FortiGate NGFW",
    category="firewall",
    api_prefix="/api/vendor/fortinet",
    log_source_types=["firewall", "fortinet"],
    alert_format="fortinet",
    auth_scheme="api_key",
    capabilities=["block_ip", "unblock_ip", "add_address_object", "get_logs"],
    field_aliases={
        "src_ip": "srcip",
        "dst_ip": "dstip",
        "action": "action",
    },
    metadata={"base_path": "/api/vendor/fortinet"},
)


# ── Master Registry ───────────────────────────────────────────────────────────

ALL_PERSONAS: dict[str, PersonaDefinition] = {
    p.key: p for p in [
        CROWDSTRIKE_FALCON, CARBON_BLACK, MICROSOFT_DEFENDER, SENTINELONE, ELASTIC_EDR,
        SPLUNK_ES, QRADAR, PALO_ALTO_XSIAM, MICROSOFT_SENTINEL, ELASTIC_SIEM,
        OKTA, MICROSOFT_ENTRA,
        PALO_ALTO_NGFW, FORTINET,
    ]
}

PERSONAS_BY_CATEGORY: dict[str, list[PersonaDefinition]] = {}
for _p in ALL_PERSONAS.values():
    PERSONAS_BY_CATEGORY.setdefault(_p.category, []).append(_p)


# ── Default stack for each security tier ──────────────────────────────────────

DEFAULT_STACK: dict[str, str] = {
    "edr":      "crowdstrike_falcon",
    "siem":     "splunk_es",
    "idp":      "okta",
    "firewall": "palo_alto_ngfw",
}


def get_persona(key: str) -> PersonaDefinition | None:
    return ALL_PERSONAS.get(key)


def get_stack_for_environment(env_settings: dict) -> dict[str, PersonaDefinition]:
    """Return the full persona stack for an environment given its settings dict."""
    stack = {}
    for category, default_key in DEFAULT_STACK.items():
        chosen = env_settings.get(f"{category}_persona", default_key)
        stack[category] = ALL_PERSONAS.get(chosen) or ALL_PERSONAS[default_key]
    return stack


def personas_to_api_spec(stack: dict[str, PersonaDefinition]) -> dict:
    """Describe the simulated API endpoints for a given stack (for Joti auto-discovery)."""
    return {
        category: {
            "vendor": p.vendor,
            "product": p.product,
            "api_base": p.api_prefix,
            "auth_scheme": p.auth_scheme,
            "capabilities": p.capabilities,
        }
        for category, p in stack.items()
    }
