"""Cloud provider vendor-specific benign event templates.

Sourced from official vendor documentation:
- AWS CloudTrail: eventVersion 1.08 schema (eventName, userIdentity, awsRegion, etc.)
- AWS VPC Flow Logs: Default format (version 2), space-delimited
- Azure Activity Log: operationName, caller, callerIpAddress, resultType, resourceId
- Azure Entra ID SigninLogs: UserPrincipalName, AppDisplayName, Status, DeviceDetail
- GCP Cloud Audit Logs: protoPayload.serviceName/methodName/authenticationInfo
"""
from __future__ import annotations

from typing import Any

VENDOR_BENIGN_TEMPLATES: dict[str, list[dict[str, Any]]] = {

    # ── Amazon Web Services ──────────────────────────────────────────────────
    "aws": [
        {
            "severity": "info",
            "title_template": "CloudTrail: AssumeRole — {cloud_user} in {aws_region}",
            "payload_template": {
                "eventVersion": "1.08",
                "eventTime": "{timestamp}",
                "eventID": "12345678-1234-1234-1234-123456789012",
                "eventName": "AssumeRole",
                "eventSource": "sts.amazonaws.com",
                "eventType": "AwsApiCall",
                "awsRegion": "{aws_region}",
                "sourceIPAddress": "{src_ip}",
                "userAgent": "aws-cli/2.13.0 Python/3.11.0",
                "userIdentity.type": "IAMUser",
                "userIdentity.principalId": "AIDACKCEVSQ6C2EXAMPLE",
                "userIdentity.arn": "arn:aws:iam::123456789012:user/{cloud_user}",
                "userIdentity.accountId": "123456789012",
                "userIdentity.sessionContext.attributes.mfaAuthenticated": "true",
                "requestParameters.roleArn": "arn:aws:iam::123456789012:role/DevOpsRole",
                "requestParameters.roleSessionName": "{cloud_user}-session",
                "responseElements.assumedRoleUser.arn": "arn:aws:sts::123456789012:assumed-role/DevOpsRole/{cloud_user}-session",
                "errorCode": "",
            },
        },
        {
            "severity": "info",
            "title_template": "CloudTrail: DescribeInstances — {cloud_user} in {aws_region}",
            "payload_template": {
                "eventVersion": "1.08",
                "eventTime": "{timestamp}",
                "eventName": "DescribeInstances",
                "eventSource": "ec2.amazonaws.com",
                "awsRegion": "{aws_region}",
                "sourceIPAddress": "{src_ip}",
                "userAgent": "aws-sdk-python/1.26.0",
                "userIdentity.type": "AssumedRole",
                "userIdentity.arn": "arn:aws:sts::123456789012:assumed-role/DevOpsRole/{cloud_user}",
                "userIdentity.accountId": "123456789012",
                "requestParameters.filterSet.items": [{"name": "instance-state-name", "valueSet": {"items": [{"value": "running"}]}}],
                "errorCode": "",
            },
        },
        {
            "severity": "info",
            "title_template": "CloudTrail: GetObject — {cloud_user} → s3://{s3_bucket}",
            "payload_template": {
                "eventVersion": "1.08",
                "eventTime": "{timestamp}",
                "eventName": "GetObject",
                "eventSource": "s3.amazonaws.com",
                "awsRegion": "{aws_region}",
                "sourceIPAddress": "{src_ip}",
                "userAgent": "aws-internal/3",
                "userIdentity.type": "IAMUser",
                "userIdentity.arn": "arn:aws:iam::123456789012:user/{cloud_user}",
                "userIdentity.accountId": "123456789012",
                "requestParameters.bucketName": "{s3_bucket}",
                "requestParameters.key": "configs/app.yaml",
                "errorCode": "",
            },
        },
        {
            "severity": "info",
            "title_template": "VPC Flow: ACCEPT — {src_ip}:{sport} → {server_ip}:443",
            "payload_template": {
                "_sourcetype": "aws:vpc:flowlogs",
                "version": "2",
                "account-id": "123456789012",
                "interface-id": "eni-1235b8ca123456789",
                "srcaddr": "{src_ip}",
                "dstaddr": "{server_ip}",
                "srcport": "52841",
                "dstport": "443",
                "protocol": "6",
                "packets": "20",
                "bytes": "4249",
                "start": "1718284800",
                "end": "1718284860",
                "action": "ACCEPT",
                "log-status": "OK",
            },
        },
        {
            "severity": "info",
            "title_template": "CloudTrail: PutMetricAlarm — {cloud_user} CloudWatch",
            "payload_template": {
                "eventVersion": "1.08",
                "eventTime": "{timestamp}",
                "eventName": "PutMetricAlarm",
                "eventSource": "monitoring.amazonaws.com",
                "awsRegion": "{aws_region}",
                "sourceIPAddress": "{src_ip}",
                "userIdentity.type": "IAMUser",
                "userIdentity.arn": "arn:aws:iam::123456789012:user/{cloud_user}",
                "requestParameters.alarmName": "HighCPUAlarm",
                "requestParameters.metricName": "CPUUtilization",
                "requestParameters.threshold": "80",
                "errorCode": "",
            },
        },
    ],

    # ── Microsoft Azure ──────────────────────────────────────────────────────
    "azure": [
        {
            "severity": "info",
            "title_template": "Azure Activity: Microsoft.Compute/virtualMachines/start — {username}",
            "payload_template": {
                "time": "{timestamp}",
                "correlationId": "bbbb1111-cc22-3333-44dd-555555eeeeee",
                "operationName": "Microsoft.Compute/virtualMachines/start/action",
                "operationName_value": "Start Virtual Machine",
                "resourceType": "Microsoft.Compute/virtualMachines",
                "resourceId": "/subscriptions/aaaa0a0a-bb1b-cc2c-dd3d-eeeeee4e4e4e/resourceGroups/PROD-RG/providers/Microsoft.Compute/virtualMachines/{hostname}",
                "category": "Administrative",
                "level": "Informational",
                "resultType": "Success",
                "status": "Succeeded",
                "caller": "{email}",
                "callerIpAddress": "{src_ip}",
                "subscriptionId": "aaaa0a0a-bb1b-cc2c-dd3d-eeeeee4e4e4e",
                "tenantId": "cccc2222-dd33-4444-55ee-666666ffffff",
            },
        },
        {
            "severity": "info",
            "title_template": "Azure Activity: Microsoft.Storage/storageAccounts/listKeys — {username}",
            "payload_template": {
                "time": "{timestamp}",
                "operationName": "Microsoft.Storage/storageAccounts/listKeys/action",
                "resourceType": "Microsoft.Storage/storageAccounts",
                "resourceId": "/subscriptions/aaaa0a0a-bb1b-cc2c-dd3d-eeeeee4e4e4e/resourceGroups/PROD-RG/providers/Microsoft.Storage/storageAccounts/{s3_bucket}",
                "category": "Administrative",
                "level": "Informational",
                "resultType": "Success",
                "status": "Succeeded",
                "caller": "{email}",
                "callerIpAddress": "{src_ip}",
            },
        },
        {
            "severity": "info",
            "title_template": "Azure Entra ID: SignIn — {username} → SharePoint Online",
            "payload_template": {
                "_sourcetype": "ms:aad:signin",
                "UserPrincipalName": "{email}",
                "UserDisplayName": "{username}",
                "IPAddress": "{src_ip}",
                "AppDisplayName": "SharePoint Online",
                "AppId": "00000003-0000-0ff1-ce00-000000000000",
                "ResourceDisplayName": "Microsoft Graph",
                "CreatedDateTime": "{timestamp}",
                "Status_errorCode": "0",
                "ResultType": "0",
                "AuthenticationRequirement": "multiFactorAuthentication",
                "ConditionalAccessStatus": "success",
                "RiskState": "none",
                "RiskLevelAggregated": "none",
                "ClientAppUsed": "Browser",
                "DeviceDetail_displayName": "{hostname}",
                "DeviceDetail_operatingSystem": "Windows 10",
                "IsInteractive": True,
                "UserType": "Member",
            },
        },
        {
            "severity": "info",
            "title_template": "Azure Activity: Microsoft.KeyVault/vaults/read — {username}",
            "payload_template": {
                "time": "{timestamp}",
                "operationName": "Microsoft.KeyVault/vaults/read",
                "resourceType": "Microsoft.KeyVault/vaults",
                "category": "Administrative",
                "level": "Informational",
                "resultType": "Success",
                "caller": "{email}",
                "callerIpAddress": "{src_ip}",
            },
        },
    ],

    # ── Google Cloud Platform ────────────────────────────────────────────────
    "gcp": [
        {
            "severity": "info",
            "title_template": "GCP Audit: compute.instances.insert — {cloud_user}",
            "payload_template": {
                "protoPayload.@type": "type.googleapis.com/google.cloud.audit.AuditLog",
                "protoPayload.serviceName": "compute.googleapis.com",
                "protoPayload.methodName": "beta.compute.instances.insert",
                "protoPayload.resourceName": "projects/my-project/zones/us-central1-a/instances/{hostname}",
                "protoPayload.authenticationInfo.principalEmail": "{email}",
                "protoPayload.requestMetadata.callerIp": "{src_ip}",
                "protoPayload.requestMetadata.callerSuppliedUserAgent": "google-cloud-sdk/425.0.0",
                "protoPayload.authorizationInfo[0].permission": "compute.instances.create",
                "protoPayload.authorizationInfo[0].granted": True,
                "protoPayload.status.code": 0,
                "timestamp": "{timestamp}",
                "severity": "NOTICE",
                "logName": "projects/my-project/logs/cloudaudit.googleapis.com",
                "insertId": "12345678-1234-1234-1234-123456789012",
            },
        },
        {
            "severity": "info",
            "title_template": "GCP Audit: storage.objects.get — {cloud_user} → {s3_bucket}",
            "payload_template": {
                "protoPayload.serviceName": "storage.googleapis.com",
                "protoPayload.methodName": "storage.objects.get",
                "protoPayload.resourceName": "projects/_/buckets/{s3_bucket}/objects/configs/app.yaml",
                "protoPayload.authenticationInfo.principalEmail": "{email}",
                "protoPayload.requestMetadata.callerIp": "{src_ip}",
                "protoPayload.status.code": 0,
                "timestamp": "{timestamp}",
                "severity": "INFO",
            },
        },
        {
            "severity": "info",
            "title_template": "GCP Audit: iam.serviceAccounts.actAs — {cloud_user}",
            "payload_template": {
                "protoPayload.serviceName": "iam.googleapis.com",
                "protoPayload.methodName": "google.iam.admin.v1.GetServiceAccount",
                "protoPayload.resourceName": "projects/my-project/serviceAccounts/app-service-account@my-project.iam.gserviceaccount.com",
                "protoPayload.authenticationInfo.principalEmail": "{email}",
                "protoPayload.requestMetadata.callerIp": "{src_ip}",
                "protoPayload.status.code": 0,
                "timestamp": "{timestamp}",
                "severity": "INFO",
            },
        },
    ],
}
