"""Network security vendor-specific benign event templates.

Sourced from official vendor documentation:
- Palo Alto Networks: Traffic log CSV fields (pan:traffic sourcetype)
- Fortinet FortiGate: Key=value traffic log (fgt_traffic sourcetype)
- Check Point: Action/src/dst log format (cp:firewall sourcetype)
- Cisco ASA: Syslog message format %ASA-6-302013 (cisco:asa sourcetype)
- Zscaler ZIA: JSON web log (zscaler:zia sourcetype)
- Cloudflare WAF/CDN: JSON HTTP request log (cloudflare:logpush sourcetype)
- Cisco IOS: Interface/spanning-tree syslog (cisco:ios sourcetype)
"""
from __future__ import annotations

from typing import Any

# Common benign sites for firewall/proxy traffic
_BENIGN_SITES = [
    "microsoft.com", "teams.microsoft.com", "office365.com", "outlook.office365.com",
    "windowsupdate.com", "update.microsoft.com", "zoom.us", "zoom.com",
    "github.com", "api.github.com", "slack.com", "api.slack.com",
    "google.com", "accounts.google.com", "okta.com", "login.okta.com",
]

VENDOR_BENIGN_TEMPLATES: dict[str, list[dict[str, Any]]] = {

    # ── Palo Alto Networks NGFW ─────────────────────────────────────────────
    "palo_alto": [
        {
            "severity": "info",
            "title_template": "PAN: Traffic allow — {src_ip}:{sport} → teams.microsoft.com:443",
            "payload_template": {
                "receive_time": "{timestamp}",
                "serial": "PA-5220-01",
                "type": "TRAFFIC",
                "subtype": "end",
                "time_generated": "{timestamp}",
                "src": "{src_ip}",
                "dst": "52.112.0.1",
                "natsrc": "{src_ip}",
                "natdst": "52.112.0.1",
                "rule": "Allow_Internet_Traffic",
                "srcuser": "{domain}\\{username}",
                "dstuser": "",
                "app": "ms-teams-base",
                "vsys": "vsys1",
                "from": "trust",
                "to": "untrust",
                "inbound_if": "ae1.100",
                "outbound_if": "ae2",
                "sport": "52841",
                "dport": "443",
                "natsport": "52841",
                "natdport": "443",
                "flags": "0x400000",
                "proto": "6",
                "action": "allow",
                "bytes": "41748",
                "bytes_sent": "1850",
                "bytes_received": "39898",
                "packets": "62",
                "elapsed": "120",
                "category": "collaboration",
                "session_id": "12345",
            },
        },
        {
            "severity": "info",
            "title_template": "PAN: Traffic allow — {src_ip} → windowsupdate.com:443",
            "payload_template": {
                "receive_time": "{timestamp}",
                "serial": "PA-5220-01",
                "type": "TRAFFIC",
                "subtype": "end",
                "src": "{src_ip}",
                "dst": "13.107.4.50",
                "rule": "Allow_WindowsUpdate",
                "srcuser": "{domain}\\{username}",
                "app": "ms-update",
                "from": "trust",
                "to": "untrust",
                "sport": "54120",
                "dport": "443",
                "proto": "6",
                "action": "allow",
                "bytes": "2456789",
                "bytes_sent": "12540",
                "bytes_received": "2444249",
                "packets": "1820",
                "elapsed": "540",
                "category": "software-update",
            },
        },
        {
            "severity": "info",
            "title_template": "PAN: DNS allow — {src_ip} → DNS:53",
            "payload_template": {
                "receive_time": "{timestamp}",
                "serial": "PA-5220-01",
                "type": "TRAFFIC",
                "subtype": "end",
                "src": "{src_ip}",
                "dst": "{server_ip}",
                "rule": "Allow_Internal_DNS",
                "app": "dns",
                "from": "trust",
                "to": "trust",
                "sport": "55234",
                "dport": "53",
                "proto": "17",
                "action": "allow",
                "bytes": "180",
                "packets": "2",
                "elapsed": "0",
                "category": "networking",
            },
        },
    ],

    # ── Fortinet FortiGate ──────────────────────────────────────────────────
    "fortinet": [
        {
            "severity": "info",
            "title_template": "FortiGate: Allow — {src_ip} → {dst_ip}:443 (HTTPS)",
            "payload_template": {
                "date": "{date}",
                "time": "{time}",
                "devname": "FGT-HQ-01",
                "devid": "FG201FT920901892",
                "logid": "0000000013",
                "type": "traffic",
                "subtype": "forward",
                "level": "notice",
                "vd": "vdom1",
                "srcip": "{src_ip}",
                "srcport": "52841",
                "srcintf": "port1",
                "dstip": "13.107.42.14",
                "dstport": "443",
                "dstintf": "port2",
                "policyid": "1",
                "policytype": "policy",
                "policyname": "Allow_Internet",
                "action": "accept",
                "service": "HTTPS",
                "proto": "6",
                "sentbyte": "1850",
                "rcvdbyte": "39898",
                "sentpkt": "31",
                "rcvdpkt": "62",
                "duration": "120",
                "app": "HTTPS",
                "appcat": "Web.Client",
                "utmaction": "allow",
                "user": "{username}",
            },
        },
        {
            "severity": "info",
            "title_template": "FortiGate: Allow — {src_ip} → DNS:53",
            "payload_template": {
                "date": "{date}",
                "time": "{time}",
                "devname": "FGT-HQ-01",
                "logid": "0000000013",
                "type": "traffic",
                "subtype": "forward",
                "level": "notice",
                "srcip": "{src_ip}",
                "srcport": "55234",
                "dstip": "{server_ip}",
                "dstport": "53",
                "policyid": "5",
                "action": "accept",
                "service": "DNS",
                "proto": "17",
                "sentbyte": "90",
                "rcvdbyte": "90",
                "duration": "0",
            },
        },
        {
            "severity": "info",
            "title_template": "FortiGate: Allow — {src_ip} → zoom.us:443 (video)",
            "payload_template": {
                "date": "{date}",
                "time": "{time}",
                "devname": "FGT-HQ-01",
                "srcip": "{src_ip}",
                "srcport": "53122",
                "dstip": "170.114.52.2",
                "dstport": "443",
                "action": "accept",
                "app": "zoom",
                "appcat": "Video/Audio",
                "sentbyte": "120450",
                "rcvdbyte": "980234",
                "duration": "3600",
            },
        },
    ],

    # ── Check Point ─────────────────────────────────────────────────────────
    "checkpoint": [
        {
            "severity": "info",
            "title_template": "Check Point: Accept — {src_ip} → {dst_ip}:443",
            "payload_template": {
                "action": "Accept",
                "src": "{src_ip}",
                "dst": "13.107.42.14",
                "s_port": "52841",
                "service": "https",
                "service_id": "https",
                "rule_name": "Allow_Outbound_HTTPS",
                "rule_uid": "{00000000-0000-0000-0000-000000000001}",
                "ifdir": "outbound",
                "ifname": "eth1",
                "origin": "{server_ip}",
                "inzone": "Internal",
                "outzone": "External",
                "proto": "6",
                "conn_direction": "outbound",
                "time": "{timestamp}",
                "bytes": "41748",
            },
        },
        {
            "severity": "info",
            "title_template": "Check Point: Accept — {src_ip} → DNS:53",
            "payload_template": {
                "action": "Accept",
                "src": "{src_ip}",
                "dst": "{server_ip}",
                "s_port": "55234",
                "service": "dns",
                "rule_name": "Allow_Internal_DNS",
                "ifdir": "inbound",
                "ifname": "eth0",
                "inzone": "Internal",
                "outzone": "Internal",
                "proto": "17",
                "time": "{timestamp}",
            },
        },
    ],

    # ── Cisco ASA ───────────────────────────────────────────────────────────
    "cisco_asa": [
        {
            "severity": "info",
            "title_template": "ASA-6-302013: Built TCP connection {src_ip} → 13.107.42.14:443",
            "payload_template": {
                "cisco_message_id": "302013",
                "severity_level": "6",
                "action": "Built",
                "direction": "outbound",
                "proto": "TCP",
                "connection_id": "12345",
                "src_interface": "inside",
                "src_ip": "{src_ip}",
                "src_port": "52841",
                "dst_interface": "outside",
                "dst_ip": "13.107.42.14",
                "dst_port": "443",
                "nat_src_ip": "203.0.113.50",
                "nat_src_port": "52841",
                "raw_message": "%ASA-6-302013: Built outbound TCP connection 12345 for outside:13.107.42.14/443 (13.107.42.14/443) to inside:{src_ip}/52841 (203.0.113.50/52841)",
            },
        },
        {
            "severity": "info",
            "title_template": "ASA-6-302014: Teardown TCP connection {src_ip} → 13.107.42.14:443",
            "payload_template": {
                "cisco_message_id": "302014",
                "severity_level": "6",
                "action": "Teardown",
                "reason": "TCP FINs",
                "proto": "TCP",
                "connection_id": "12345",
                "src_ip": "{src_ip}",
                "src_port": "52841",
                "dst_ip": "13.107.42.14",
                "dst_port": "443",
                "duration": "0:02:00",
                "bytes": "41748",
                "raw_message": "%ASA-6-302014: Teardown TCP connection 12345 for outside:13.107.42.14/443 to inside:{src_ip}/52841 duration 0:02:00 bytes 41748 TCP FINs",
            },
        },
    ],

    # ── Zscaler ZIA ─────────────────────────────────────────────────────────
    "zscaler": [
        {
            "severity": "info",
            "title_template": "Zscaler: Allowed — {username} → {benign_site}",
            "payload_template": {
                "datetime": "{timestamp}",
                "user": "{email}",
                "srcip": "{src_ip}",
                "dstip": "13.107.42.14",
                "hostname": "teams.microsoft.com",
                "url": "https://teams.microsoft.com/api/mt/amer/beta/users/me",
                "action": "Allowed",
                "reason": "Any",
                "category": "Collaboration",
                "threat": "",
                "respcode": "200",
                "requestsize": "1024",
                "responsesize": "8192",
                "location": "Seattle HQ",
                "department": "Engineering",
                "proto": "HTTPS",
                "urlcategory": "Collaboration",
                "malwareclass": "",
                "malwarecategory": "",
                "devicename": "{hostname}",
            },
        },
        {
            "severity": "info",
            "title_template": "Zscaler: Allowed — {username} → windowsupdate.com",
            "payload_template": {
                "datetime": "{timestamp}",
                "user": "{email}",
                "srcip": "{src_ip}",
                "hostname": "windowsupdate.com",
                "url": "https://windowsupdate.com/v9/windowsupdate/redir/muv4wuredir.cab",
                "action": "Allowed",
                "category": "Software Update",
                "respcode": "200",
                "requestsize": "512",
                "responsesize": "2456789",
                "location": "Seattle HQ",
                "department": "IT",
                "devicename": "{hostname}",
            },
        },
        {
            "severity": "info",
            "title_template": "Zscaler: Allowed — {username} → github.com (dev activity)",
            "payload_template": {
                "datetime": "{timestamp}",
                "user": "{email}",
                "srcip": "{src_ip}",
                "hostname": "github.com",
                "url": "https://github.com/",
                "action": "Allowed",
                "category": "Software/Technology",
                "respcode": "200",
                "requestsize": "2048",
                "responsesize": "15360",
                "location": "Seattle HQ",
                "department": "Engineering",
                "devicename": "{hostname}",
            },
        },
    ],

    # ── Cloudflare WAF/CDN ──────────────────────────────────────────────────
    "cloudflare": [
        {
            "severity": "info",
            "title_template": "Cloudflare: GET / from {src_ip} — 200 OK (cache HIT)",
            "payload_template": {
                "ClientIP": "{src_ip}",
                "ClientRequestHost": "{domain}",
                "ClientRequestMethod": "GET",
                "ClientRequestURI": "/",
                "EdgeResponseStatus": 200,
                "EdgeResponseBytes": 1895,
                "RayID": "5e1b95b9ea390cc5",
                "Datetime": "{timestamp}",
                "CacheCacheStatus": "HIT",
                "HTTPProtocol": "HTTP/2",
                "WAFAction": "allow",
                "WAFRuleID": "",
                "ClientCountry": "US",
                "ClientDeviceType": "desktop",
                "EdgeServerIP": "162.159.135.42",
                "OriginIP": "{server_ip}",
            },
        },
        {
            "severity": "info",
            "title_template": "Cloudflare: GET /api/v1/ from {src_ip} — 200 OK",
            "payload_template": {
                "ClientIP": "{src_ip}",
                "ClientRequestHost": "{domain}",
                "ClientRequestMethod": "GET",
                "ClientRequestURI": "/api/v1/health",
                "EdgeResponseStatus": 200,
                "EdgeResponseBytes": 256,
                "RayID": "6f2c06caf9401dd5",
                "Datetime": "{timestamp}",
                "CacheCacheStatus": "MISS",
                "HTTPProtocol": "HTTP/2",
                "WAFAction": "allow",
                "ClientCountry": "US",
            },
        },
    ],

    # ── Cisco IOS Switch ─────────────────────────────────────────────────────
    "cisco_ios": [
        {
            "severity": "info",
            "title_template": "Cisco IOS: Interface GigabitEthernet0/1 up",
            "payload_template": {
                "facility": "LINEPROTO",
                "severity_level": "5",
                "message_id": "UPDOWN",
                "interface": "GigabitEthernet0/1",
                "state": "up",
                "device_hostname": "core-switch-01",
                "device_ip": "{server_ip}",
                "raw_message": "%LINEPROTO-5-UPDOWN: Line protocol on Interface GigabitEthernet0/1, changed state to up",
            },
        },
        {
            "severity": "info",
            "title_template": "Cisco IOS: MAC address learned on GigabitEthernet0/5",
            "payload_template": {
                "facility": "MAC",
                "severity_level": "6",
                "message_id": "MOVE",
                "mac_address": "00:11:22:33:44:55",
                "vlan_id": "100",
                "interface": "GigabitEthernet0/5",
                "device_hostname": "access-switch-01",
                "device_ip": "{server_ip}",
                "raw_message": "%MAC-6-MOVE: MAC address 00:11:22:33:44:55 moved from GigabitEthernet0/1 to GigabitEthernet0/5 (VLAN 100)",
            },
        },
    ],

    # ── Cisco NX-OS ─────────────────────────────────────────────────────────
    "cisco_nxos": [
        {
            "severity": "info",
            "title_template": "NX-OS: Ethernet1/5 link state change",
            "payload_template": {
                "facility": "ETH_PORT_CHANNEL",
                "severity_level": "5",
                "message_id": "PORT_UP",
                "interface": "Ethernet1/5",
                "state": "up",
                "device_hostname": "nexus-core-01",
                "device_ip": "{server_ip}",
                "raw_message": "%ETH_PORT_CHANNEL-5-PORT_UP: port-channel1: Ethernet1/5 is up",
            },
        },
    ],
}
