"""Log source generation endpoints — v2 API.

Powered by the agentic log generator: schemas live in ChromaDB,
events are generated by Claude and cached in Redis/memory.
Never uses hardcoded event templates.
"""
from __future__ import annotations

import uuid
from typing import Any

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

router = APIRouter(prefix="/log-sources", tags=["log-sources"])


# ---------------------------------------------------------------------------
# Request/response models
# ---------------------------------------------------------------------------

class GenerateRequest(BaseModel):
    source_id: str = Field(
        ..., description="Log source ID (e.g. 'windows_sysmon', 'aws_cloudtrail')."
    )
    technique_id: str = Field(
        ..., description="MITRE ATT&CK technique ID (e.g. 'T1059.001')."
    )
    count: int = Field(10, ge=1, le=500, description="Number of events to generate.")
    snr_ratio: float = Field(
        1.0, ge=0.0, le=1.0,
        description="Signal-to-noise ratio. 1.0 = all attack. 0.1 = 10% attack + 90% noise.",
    )
    force_refresh: bool = Field(
        False, description="Bypass cache and regenerate from Claude."
    )


class ChainRunRequest(BaseModel):
    chain_id: str | None = Field(
        None, description="Built-in chain ID (use /attack-chains/list to enumerate)."
    )
    chain_yaml: str | None = Field(
        None, description="YAML definition for a custom attack chain."
    )
    simulate_delays: bool = Field(
        False, description="Apply real delays between stages (for SIEM streaming)."
    )
    parallelise: bool = Field(
        False, description="Run independent stages in parallel."
    )


class LogSourceCreateRequest(BaseModel):
    name: str = Field(..., max_length=255)
    source_type: str = Field(..., max_length=50)
    schema_definition: dict[str, Any] | None = Field(None)
    sample_log: dict[str, Any] | None = Field(None)
    enabled: bool = Field(True)
    description: str = Field("", max_length=1000)


# ---------------------------------------------------------------------------
# Generator catalog
# ---------------------------------------------------------------------------

# Category display names and descriptions for each generator
_GENERATOR_META: dict[str, dict[str, Any]] = {
    "splunk": {
        "name": "Splunk SIEM",
        "category": "siem",
        "description": "Splunk HEC-format alerts and search results with CIM compliance.",
        "supported_fields": ["_time", "host", "source", "sourcetype", "index", "event", "severity", "rule_name"],
    },
    "crowdstrike": {
        "name": "CrowdStrike Falcon",
        "category": "edr",
        "description": "CrowdStrike Falcon Streaming API DetectionSummaryEvent format.",
        "supported_fields": ["DetectId", "DetectName", "Severity", "ComputerName", "UserName", "Tactic", "Technique", "TechniqueId", "CommandLine", "SHA256String"],
    },
    "sentinel": {
        "name": "Microsoft Sentinel",
        "category": "siem",
        "description": "Azure Sentinel security alerts via Log Analytics workspace.",
        "supported_fields": ["TimeGenerated", "AlertName", "AlertSeverity", "ProviderName", "Entities", "ExtendedProperties"],
    },
    "okta": {
        "name": "Okta Identity",
        "category": "identity",
        "description": "Okta system log events for authentication and directory activity.",
        "supported_fields": ["uuid", "eventType", "actor", "target", "outcome", "displayMessage", "severity", "client"],
    },
    "proofpoint": {
        "name": "Proofpoint Email Security",
        "category": "email",
        "description": "Proofpoint TRAP/SIEM API message and click events.",
        "supported_fields": ["messageId", "subject", "sender", "recipients", "phishScore", "spamScore", "verdict", "threatsInfoMap"],
    },
    "servicenow": {
        "name": "ServiceNow ITSM",
        "category": "itsm",
        "description": "ServiceNow Security Incident Response (SIR) ticket records.",
        "supported_fields": ["number", "category", "priority", "state", "assignment_group", "short_description", "caller_id", "cmdb_ci"],
    },
    "carbon_black": {
        "name": "VMware Carbon Black",
        "category": "edr",
        "description": "Carbon Black Cloud alert and process events via CB Response API.",
        "supported_fields": ["id", "alert_severity", "reason", "device_name", "process_name", "process_cmdline", "ioc_hit", "threat_id"],
    },
    "defender_endpoint": {
        "name": "Microsoft Defender for Endpoint",
        "category": "edr",
        "description": "MDE Advanced Hunting / Alert API events.",
        "supported_fields": ["AlertId", "Title", "Severity", "Category", "DeviceName", "ProcessCommandLine", "RemoteUrl", "SHA256"],
    },
    "entra_id": {
        "name": "Microsoft Entra ID",
        "category": "identity",
        "description": "Azure AD / Entra sign-in and audit log events.",
        "supported_fields": ["correlationId", "createdDateTime", "userPrincipalName", "appDisplayName", "ipAddress", "status", "riskDetail"],
    },
    "qradar": {
        "name": "IBM QRadar SIEM",
        "category": "siem",
        "description": "QRadar offense and event records via REST API.",
        "supported_fields": ["id", "offense_type", "severity", "magnitude", "status", "source_address_ids", "destination_networks", "category"],
    },
    "elastic": {
        "name": "Elastic Security",
        "category": "siem",
        "description": "Elasticsearch ECS-format security alerts and signals.",
        "supported_fields": ["@timestamp", "event.action", "event.category", "event.severity", "host.name", "user.name", "process.name", "kibana.alert.rule.name"],
    },
    "guardduty": {
        "name": "AWS GuardDuty",
        "category": "cloud",
        "description": "AWS GuardDuty threat detection findings via CloudWatch Events.",
        "supported_fields": ["id", "type", "severity", "accountId", "region", "service.action", "resource", "description"],
    },
}


@router.get("/generators")
async def list_generators():
    """List all available event generators from GENERATOR_REGISTRY with metadata and a live sample event."""
    from backend.engine.generators import GENERATOR_REGISTRY
    from backend.engine.generators.base import GeneratorConfig

    results = []
    for gen_id, gen_class in GENERATOR_REGISTRY.items():
        meta = _GENERATOR_META.get(gen_id, {})

        # Generate a live sample event
        sample_event: dict[str, Any] | None = None
        try:
            cfg = GeneratorConfig(
                product_type=gen_id,
                target_url="http://localhost:8080",
            )
            instance = gen_class(cfg)
            sample_event = instance.generate()
        except Exception:
            sample_event = None

        results.append({
            "id": gen_id,
            "name": meta.get("name", gen_class.product_name),
            "category": meta.get("category", gen_class.product_category),
            "description": meta.get("description", ""),
            "supported_fields": meta.get("supported_fields", []),
            "sample_event": sample_event,
        })

    # Sort by category then name
    results.sort(key=lambda x: (x["category"], x["name"]))
    return {"count": len(results), "generators": results}


# ---------------------------------------------------------------------------
# Schema registry (existing)
# ---------------------------------------------------------------------------

@router.get("/sources")
async def list_sources(category: str | None = Query(None)):
    """List all registered log sources with MITRE mappings and SIEM metadata."""
    from backend.log_sources.agentic_generator import get_generator
    gen = get_generator()
    sources = await gen.list_sources()
    if category:
        sources = [s for s in sources if s["category"] == category]
    return {"count": len(sources), "sources": sources}


@router.get("/sources/{source_id}")
async def get_source(source_id: str):
    """Return full schema definition for a specific source."""
    from backend.log_sources.schema_registry import get_registry
    reg = get_registry()
    schema = reg.get(source_id)
    if not schema:
        raise HTTPException(404, detail=f"Source '{source_id}' not found.")
    from dataclasses import asdict
    return asdict(schema)


@router.get("/sources/{source_id}/techniques")
async def get_source_techniques(source_id: str):
    """List MITRE techniques mapped to a source."""
    from backend.log_sources.schema_registry import get_registry
    reg = get_registry()
    schema = reg.get(source_id)
    if not schema:
        raise HTTPException(404, detail=f"Source '{source_id}' not found.")
    return {
        "source_id": source_id,
        "techniques": [
            {"technique_id": tid, "event_types": etypes}
            for tid, etypes in schema.mitre_mappings.items()
        ],
    }


# ---------------------------------------------------------------------------
# Log source schema CRUD (DB-backed)
# ---------------------------------------------------------------------------

@router.get("")
async def list_log_source_schemas():
    """List all configured log source schemas from the database."""
    try:
        from backend.db.session import async_session
        from backend.db.models import LogSourceSchema
        from sqlalchemy import select

        async with async_session() as session:
            result = await session.execute(
                select(LogSourceSchema).order_by(LogSourceSchema.created_at.desc())
            )
            schemas = result.scalars().all()
            return {
                "count": len(schemas),
                "log_sources": [_schema_to_dict(s) for s in schemas],
            }
    except Exception as exc:
        # DB not yet wired — return empty list gracefully
        return {"count": 0, "log_sources": [], "warning": str(exc)}


@router.post("")
async def create_log_source_schema(req: LogSourceCreateRequest):
    """Create a new log source schema configuration."""
    try:
        from backend.db.session import async_session
        from backend.db.models import LogSourceSchema

        async with async_session() as session:
            schema = LogSourceSchema(
                name=req.name,
                source_type=req.source_type,
                schema_definition=req.schema_definition or {},
                sample_event=req.sample_log or {},
                description=req.description,
            )
            session.add(schema)
            await session.commit()
            await session.refresh(schema)
            return _schema_to_dict(schema)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.put("/{schema_id}/test")
async def test_log_source_schema(schema_id: str):
    """Run a test generation for a log source schema. Returns 3 sample events."""
    try:
        from backend.db.session import async_session
        from backend.db.models import LogSourceSchema
        from sqlalchemy import select
        from backend.engine.generators import GENERATOR_REGISTRY
        from backend.engine.generators.base import GeneratorConfig

        async with async_session() as session:
            result = await session.execute(
                select(LogSourceSchema).where(LogSourceSchema.id == uuid.UUID(schema_id))
            )
            schema = result.scalar_one_or_none()

        if not schema:
            raise HTTPException(404, detail=f"Log source schema '{schema_id}' not found.")

        # Try to find a matching generator by source_type
        gen_class = GENERATOR_REGISTRY.get(schema.source_type)
        if gen_class:
            cfg = GeneratorConfig(
                product_type=schema.source_type,
                target_url="http://localhost:8080",
            )
            instance = gen_class(cfg)
            events = instance.generate_batch(3)
        else:
            # Fallback: return the stored sample event 3 times
            sample = schema.sample_event or {}
            events = [sample, sample, sample]

        return {
            "schema_id": schema_id,
            "source_type": schema.source_type,
            "events": events,
            "count": len(events),
        }
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.get("/{schema_id}/schema")
async def get_log_source_json_schema(schema_id: str):
    """Return the JSON schema for field validation of a log source."""
    try:
        from backend.db.session import async_session
        from backend.db.models import LogSourceSchema
        from sqlalchemy import select

        async with async_session() as session:
            result = await session.execute(
                select(LogSourceSchema).where(LogSourceSchema.id == uuid.UUID(schema_id))
            )
            schema = result.scalar_one_or_none()

        if not schema:
            raise HTTPException(404, detail=f"Log source schema '{schema_id}' not found.")

        return {
            "schema_id": schema_id,
            "name": schema.name,
            "source_type": schema.source_type,
            "schema_definition": schema.schema_definition or {},
        }
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


# ---------------------------------------------------------------------------
# Event generation
# ---------------------------------------------------------------------------

@router.post("/generate")
async def generate_events(req: GenerateRequest):
    """Generate synthetic attack events for a technique + source pair.

    Events are generated by Claude using the schema registry and cached
    in Redis/memory. Subsequent calls with the same parameters are fast.
    """
    from backend.log_sources.agentic_generator import get_generator
    gen = get_generator()
    result = await gen.generate(
        source_id=req.source_id,
        technique_id=req.technique_id,
        count=req.count,
        snr_ratio=req.snr_ratio,
        force_refresh=req.force_refresh,
    )
    if "error" in result:
        raise HTTPException(400, detail=result["error"])
    return result


@router.post("/generate/benign")
async def generate_benign_events(
    source_id: str,
    count: int = Query(20, ge=1, le=500),
    force_refresh: bool = Query(False),
):
    """Generate realistic benign/noise events for a source."""
    from backend.log_sources.agentic_generator import get_generator
    gen = get_generator()
    result = await gen.generate_benign(
        source_id=source_id,
        count=count,
        force_refresh=force_refresh,
    )
    if "error" in result:
        raise HTTPException(400, detail=result["error"])
    return result


@router.post("/generate/technique/{technique_id}")
async def generate_for_technique(
    technique_id: str,
    count_per_source: int = Query(5, ge=1, le=100),
    snr_ratio: float = Query(1.0, ge=0.0, le=1.0),
):
    """Generate events from ALL sources that map to a MITRE technique."""
    from backend.log_sources.schema_registry import get_registry
    from backend.log_sources.agentic_generator import get_generator
    reg = get_registry()
    gen = get_generator()

    sources = reg.get_mitre_sources(technique_id)
    if not sources:
        raise HTTPException(
            404,
            detail=f"No sources mapped to technique '{technique_id}'.",
        )

    import asyncio
    tasks = [
        gen.generate(
            source_id=s.source_id,
            technique_id=technique_id,
            count=count_per_source,
            snr_ratio=snr_ratio,
        )
        for s in sources
    ]
    results = await asyncio.gather(*tasks, return_exceptions=True)

    all_events: list[dict[str, Any]] = []
    source_summaries = []
    for s, res in zip(sources, results):
        if isinstance(res, Exception):
            source_summaries.append({"source_id": s.source_id, "error": str(res)})
        else:
            all_events.extend(res.get("events", []))
            source_summaries.append({
                "source_id": s.source_id,
                "count": res.get("count", 0),
                "cache_hit": res.get("cache_hit", False),
            })

    return {
        "technique_id": technique_id,
        "total_events": len(all_events),
        "sources": source_summaries,
        "events": all_events,
    }


# ---------------------------------------------------------------------------
# Cache management
# ---------------------------------------------------------------------------

@router.delete("/cache/{source_id}")
async def invalidate_cache(source_id: str):
    """Flush cached templates for a source (call after schema update)."""
    from backend.log_sources.agentic_generator import get_generator
    gen = get_generator()
    flushed = await gen.invalidate_source(source_id)
    return {
        "source_id": source_id,
        "templates_flushed": flushed,
        "message": f"Flushed {flushed} cached templates for '{source_id}'.",
    }


# ---------------------------------------------------------------------------
# Attack chains
# ---------------------------------------------------------------------------

@router.get("/attack-chains")
async def list_attack_chains():
    """List all built-in attack chain definitions with stage and technique counts."""
    from backend.attack_chains.orchestrator import AttackChainOrchestrator
    orch = AttackChainOrchestrator()
    raw_chains = orch.list_builtin_chains()
    # Enrich with mitre_techniques field alias
    chains = []
    for c in raw_chains:
        chains.append({
            "id": c["id"],
            "name": c["name"],
            "description": c["description"],
            "threat_actor": c.get("threat_actor"),
            "stage_count": c["stage_count"],
            "mitre_techniques": c.get("techniques", []),
        })
    return {"count": len(chains), "chains": chains}


@router.post("/attack-chains/run")
async def run_attack_chain(req: ChainRunRequest):
    """Execute an attack chain and return all generated events.

    Provide either chain_id (built-in) or chain_yaml (custom YAML).
    All events are tagged with a shared correlation_id for traceability.
    """
    from backend.attack_chains.orchestrator import AttackChainOrchestrator, AttackChain
    orch = AttackChainOrchestrator()

    if req.chain_yaml:
        chain = AttackChain.from_yaml_str(req.chain_yaml)
    elif req.chain_id:
        chain = orch.get_builtin_chain(req.chain_id)
        if not chain:
            available = [c["id"] for c in orch.list_builtin_chains()]
            raise HTTPException(
                404,
                detail=f"Chain '{req.chain_id}' not found. Available: {available}",
            )
    else:
        raise HTTPException(400, detail="Provide chain_id or chain_yaml.")

    result = await orch.run(
        chain,
        simulate_delays=req.simulate_delays,
        parallelise=req.parallelise,
    )
    return result.to_dict()


# ---------------------------------------------------------------------------
# Scoring endpoints
# ---------------------------------------------------------------------------

@router.get("/scoring/des")
async def compute_des(
    techniques: str = Query(
        ...,
        description="Comma-separated MITRE technique IDs in scope (e.g. 'T1059.001,T1078').",
    )
):
    """Compute Detection Efficacy Score (DES) from stored rule test results.

    Returns score (0-100) with component breakdown:
    breadth, depth, freshness, pass_rate, signal_quality.
    """
    from backend.scoring.des import DetectionEfficacyScore, RuleSummary
    from datetime import datetime, timezone, timedelta

    technique_list = [t.strip() for t in techniques.split(",") if t.strip()]

    # TODO: load from database when persistence is wired
    # Using demo data for now
    demo_rules = [
        RuleSummary(
            rule_id="sigma-ps-encoded",
            technique_id="T1059.001",
            total_tests=12,
            successes=10,
            last_tested_at=datetime.now(timezone.utc) - timedelta(days=5),
            false_positive_rate=0.05,
        ),
        RuleSummary(
            rule_id="sigma-valid-accounts",
            technique_id="T1078",
            total_tests=8,
            successes=7,
            last_tested_at=datetime.now(timezone.utc) - timedelta(days=15),
            false_positive_rate=0.10,
        ),
        RuleSummary(
            rule_id="sigma-lsass-dump",
            technique_id="T1003.001",
            total_tests=5,
            successes=4,
            last_tested_at=datetime.now(timezone.utc) - timedelta(days=45),
            false_positive_rate=0.02,
        ),
    ]

    scorer = DetectionEfficacyScore()
    result = scorer.compute(demo_rules, technique_list)
    return result.to_dict()


@router.get("/scoring/ihds")
async def compute_ihds(
    techniques: str = Query(
        ...,
        description="Comma-separated MITRE technique IDs in scope.",
    ),
    use_joti: bool = Query(False, description="Pull hunt score from Joti HCCS."),
):
    """Compute Intel-to-Hunt-to-Detection Score (IHDS).

    Multiplicative pipeline: Intel × Hunt × Detection.
    Any broken stage → score approaches zero.
    """
    from backend.scoring.ihds import IntelHuntDetectionScore, TTPIntelEntry, HuntEntry
    from backend.scoring.des import RuleSummary
    from datetime import datetime, timezone, timedelta

    technique_list = [t.strip() for t in techniques.split(",") if t.strip()]

    # Demo data (replace with DB queries)
    intel = [
        TTPIntelEntry("T1059.001", "APT29", datetime.now(timezone.utc) - timedelta(days=10)),
        TTPIntelEntry("T1078", "APT29", datetime.now(timezone.utc) - timedelta(days=30)),
        TTPIntelEntry("T1003.001", "Lazarus", datetime.now(timezone.utc) - timedelta(days=60)),
    ]
    hunts = [
        HuntEntry("T1059.001", "hunt-001", datetime.now(timezone.utc) - timedelta(days=7)),
        HuntEntry("T1078", "hunt-002", datetime.now(timezone.utc) - timedelta(days=20)),
    ]
    rules = [
        RuleSummary("sigma-ps-encoded", "T1059.001", 12, 10,
                    datetime.now(timezone.utc) - timedelta(days=5), 0.05),
        RuleSummary("sigma-valid-accounts", "T1078", 8, 7,
                    datetime.now(timezone.utc) - timedelta(days=15), 0.10),
    ]

    joti_hunt_score = None
    joti_used = False
    if use_joti:
        from backend.integrations.joti_client import get_joti_client
        client = get_joti_client()
        if client:
            async with client as joti:
                hccs = await joti.get_hccs()
                if hccs:
                    joti_hunt_score = hccs.score / 100.0
                    joti_used = True

    scorer = IntelHuntDetectionScore()
    result = scorer.compute(intel, hunts, rules, technique_list, joti_hunt_score)
    return result.to_dict()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _schema_to_dict(s: Any) -> dict[str, Any]:
    return {
        "id": str(s.id),
        "name": s.name,
        "source_type": s.source_type,
        "schema_definition": s.schema_definition or {},
        "sample_event": s.sample_event or {},
        "description": s.description or "",
        "created_at": s.created_at.isoformat() if s.created_at else None,
    }
