"""MCP Server HTTP endpoint — PurpleLab as an industry-standard MCP server.

Supports three transports so any MCP client can connect:

  1. HTTP JSON-RPC (POST /api/v2/mcp)
     Used by: Joti MCP Hub, custom integrations, server-to-server calls.

  2. HTTP + SSE (GET /api/v2/mcp/sse  +  POST /api/v2/mcp/messages)
     Used by: Claude Desktop, VS Code MCP extension, Cursor, any SSE-capable client.

  3. Discovery (GET /api/v2/mcp)
     Returns tool catalogue + connection instructions without auth.

Authentication:
  Header: X-API-Key: <key>   (preferred)
  Header: Authorization: Bearer <key>

  Default dev key: purplelab-dev-key
  Production: set PURPLELAB_MCP_API_KEY env var (auto-generated by purplelab.sh)

Standard client configs are in mcp-clients.json at the project root.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import uuid
from typing import Any, AsyncGenerator, Optional

from fastapi import APIRouter, Header, HTTPException, Request
from fastapi.responses import JSONResponse, StreamingResponse

from backend.mcp.server import handle_request, TOOLS

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/mcp", tags=["mcp"])

_API_KEY = os.getenv("PURPLELAB_MCP_API_KEY", "purplelab-dev-key")

# Per-session SSE message queues: session_id → asyncio.Queue
_sse_sessions: dict[str, asyncio.Queue] = {}


def _check_auth(x_api_key: Optional[str], authorization: Optional[str]) -> Optional[str]:
    """Return the API key if valid, else None."""
    key = x_api_key
    if not key and authorization:
        if authorization.startswith("Bearer "):
            key = authorization.removeprefix("Bearer ").strip()
    return key if key == _API_KEY else None


# ── Discovery ─────────────────────────────────────────────────────────────────

@router.get("")
async def mcp_discovery():
    """No-auth discovery — returns all tools + connection instructions.

    MCP clients (Joti, Claude Desktop, etc.) call this to learn
    what tools are available before connecting.
    """
    backend_port = os.getenv("PURPLELAB_BACKEND_PORT", "8002")
    base_url = f"http://localhost:{backend_port}/api/v2/mcp"
    api_key = _API_KEY

    return {
        "server": "purplelab-mcp",
        "version": "2.0.0",
        "protocol": "mcp/2024-11-05",
        "description": (
            "PurpleLab Security Simulation Platform — simulated EDR, SIEM, "
            "Identity (Okta/Entra), and Network controls for SOC testing and "
            "purple team exercises. All containment actions are fully logged."
        ),
        "capabilities": {"tools": True, "resources": False, "prompts": False},
        "tool_count": len(TOOLS),
        "categories": {
            "edr": [t["name"] for t in TOOLS if t["name"].startswith("edr_")],
            "siem": [t["name"] for t in TOOLS if t["name"].startswith("siem_")],
            "identity": [t["name"] for t in TOOLS if t["name"].startswith("identity_")],
            "network": [t["name"] for t in TOOLS if t["name"].startswith("network_")],
            "platform": [t["name"] for t in TOOLS if not any(
                t["name"].startswith(p) for p in ("edr_", "siem_", "identity_", "network_")
            )],
        },
        "tools": [{"name": t["name"], "description": t["description"]} for t in TOOLS],
        "transports": {
            "http_jsonrpc": {
                "url": f"{base_url}",
                "method": "POST",
                "content_type": "application/json",
                "auth_header": "X-API-Key",
            },
            "sse": {
                "connect": f"{base_url}/sse",
                "messages": f"{base_url}/messages",
                "auth_header": "X-API-Key",
            },
        },
        "quick_connect": {
            "claude_code": f"claude mcp add purplelab --transport http --url {base_url} --header 'X-API-Key:{api_key}'",
            "claude_desktop_config": {
                "mcpServers": {
                    "purplelab": {
                        "transport": "http",
                        "url": base_url,
                        "headers": {"X-API-Key": api_key},
                    }
                }
            },
            "joti_registration": {
                "url": base_url.replace("localhost", "purplelab-backend").replace(backend_port, "8000"),
                "auth_type": "api_key",
                "api_key_header": "X-API-Key",
                "api_key_value": api_key,
            },
        },
    }


# ── HTTP JSON-RPC transport (server-to-server / Joti) ─────────────────────────

@router.post("")
async def mcp_jsonrpc(
    request: Request,
    x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
    authorization: Optional[str] = Header(None),
):
    """JSON-RPC 2.0 over HTTP — used by Joti, custom integrations, CLI.

    Supports single requests and batch arrays:
      {"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"...","arguments":{...}}}
      [{"jsonrpc":"2.0",...}, {"jsonrpc":"2.0",...}]
    """
    auth_key = _check_auth(x_api_key, authorization)

    try:
        body = await request.json()
    except Exception:
        return JSONResponse(
            status_code=400,
            content={"jsonrpc": "2.0", "id": None, "error": {"code": -32700, "message": "Parse error"}},
        )

    if isinstance(body, list):
        responses = [await handle_request(item, auth_key) for item in body]
        return JSONResponse(content=responses)

    response = await handle_request(body, auth_key)
    status = 401 if response.get("error", {}).get("code") == -32001 else 200
    return JSONResponse(status_code=status, content=response)


# ── SSE transport (Claude Desktop / VS Code / Cursor) ─────────────────────────

@router.get("/sse")
async def mcp_sse_connect(
    request: Request,
    x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
    authorization: Optional[str] = Header(None),
):
    """SSE connection endpoint — MCP clients open a persistent SSE stream here.

    The client then POSTs JSON-RPC messages to /api/v2/mcp/messages?session_id=<id>
    and receives responses on this stream.

    Compatible with: Claude Desktop, VS Code MCP extension, Cursor, mcp CLI.

    How to connect with Claude Code CLI:
      claude mcp add purplelab \\
        --transport sse \\
        --url http://localhost:8002/api/v2/mcp/sse \\
        --header "X-API-Key: purplelab-dev-key"
    """
    auth_key = _check_auth(x_api_key, authorization)
    if not auth_key:
        raise HTTPException(status_code=401, detail="Invalid or missing X-API-Key")

    session_id = str(uuid.uuid4())
    queue: asyncio.Queue = asyncio.Queue()
    _sse_sessions[session_id] = queue

    async def event_stream() -> AsyncGenerator[str, None]:
        # Send endpoint event so client knows where to POST messages
        messages_url = f"/api/v2/mcp/messages?session_id={session_id}"
        yield f"event: endpoint\ndata: {messages_url}\n\n"

        try:
            while True:
                if await request.is_disconnected():
                    break
                try:
                    msg = await asyncio.wait_for(queue.get(), timeout=15.0)
                    data = json.dumps(msg)
                    yield f"data: {data}\n\n"
                except asyncio.TimeoutError:
                    # Keepalive ping
                    yield ": keepalive\n\n"
        finally:
            _sse_sessions.pop(session_id, None)

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
            "X-MCP-Session-ID": session_id,
        },
    )


@router.post("/messages")
async def mcp_sse_messages(
    request: Request,
    session_id: str,
    x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
    authorization: Optional[str] = Header(None),
):
    """Receive JSON-RPC messages for an SSE session and route response back.

    The client POSTs here; responses are pushed to the SSE stream identified
    by session_id.
    """
    auth_key = _check_auth(x_api_key, authorization)
    if not auth_key:
        raise HTTPException(status_code=401, detail="Invalid or missing X-API-Key")

    queue = _sse_sessions.get(session_id)
    if not queue:
        raise HTTPException(status_code=404, detail=f"Session {session_id} not found or expired")

    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON body")

    if isinstance(body, list):
        for item in body:
            response = await handle_request(item, auth_key)
            await queue.put(response)
    else:
        response = await handle_request(body, auth_key)
        await queue.put(response)

    return JSONResponse(status_code=202, content={"accepted": True})
